CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transcription_tasks (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  external_task_id VARCHAR(128) NULL,
  meeting_id BIGINT UNSIGNED NULL,
  post_process_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  post_process_error TEXT NULL,
  post_processed_at TIMESTAMP NULL,
  sync_fail_count INT NOT NULL DEFAULT 0,
  last_sync_error TEXT NULL,
  last_sync_at TIMESTAMP NULL,
  next_sync_at TIMESTAMP NULL,
  audio_url VARCHAR(512) NOT NULL,
  local_file_path VARCHAR(1024) NULL,
  segment_total INT NOT NULL DEFAULT 0,
  segment_completed INT NOT NULL DEFAULT 0,
  result_text LONGTEXT NULL,
  duration DOUBLE NOT NULL DEFAULT 0,
  dict_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_transcription_tasks_user_id (user_id),
  KEY idx_transcription_tasks_external_task_id (external_task_id),
  KEY idx_transcription_tasks_meeting_id (meeting_id),
  KEY idx_transcription_tasks_post_process_status (post_process_status),
  KEY idx_transcription_tasks_next_sync_at (next_sync_at)
);

CREATE TABLE IF NOT EXISTS meetings (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  source_task_id BIGINT UNSIGNED NULL UNIQUE,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  audio_url VARCHAR(512) NOT NULL,
  duration DOUBLE NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'uploaded',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_meetings_user_id (user_id)
);

CREATE TABLE IF NOT EXISTS meeting_transcripts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  meeting_id BIGINT UNSIGNED NOT NULL,
  speaker_label VARCHAR(64) NOT NULL,
  text LONGTEXT NOT NULL,
  start_time DOUBLE NOT NULL DEFAULT 0,
  end_time DOUBLE NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_meeting_transcripts_meeting_id (meeting_id)
);

CREATE TABLE IF NOT EXISTS meeting_summaries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  meeting_id BIGINT UNSIGNED NOT NULL UNIQUE,
  content LONGTEXT NOT NULL,
  model_version VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS term_dicts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  domain VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_term_dicts_domain (domain)
);

CREATE TABLE IF NOT EXISTS term_entries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  dict_id BIGINT UNSIGNED NOT NULL,
  correct_term VARCHAR(255) NOT NULL,
  wrong_variants_json JSON NULL,
  pinyin VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_term_entries_dict_id (dict_id)
);

CREATE TABLE IF NOT EXISTS correction_rules (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  dict_id BIGINT UNSIGNED NOT NULL,
  layer INT NOT NULL,
  pattern VARCHAR(255) NOT NULL,
  replacement VARCHAR(255) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_correction_rules_dict_id (dict_id)
);

CREATE TABLE IF NOT EXISTS admin_operation_states (
  operation_key VARCHAR(64) PRIMARY KEY,
  payload LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);