CREATE TABLE IF NOT EXISTS filler_dicts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  scene VARCHAR(128) NOT NULL,
  description TEXT NULL,
  is_base TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_filler_dicts_scene (scene),
  KEY idx_filler_dicts_is_base (is_base)
);

CREATE TABLE IF NOT EXISTS filler_entries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  dict_id BIGINT UNSIGNED NOT NULL,
  word VARCHAR(255) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_filler_entries_dict (dict_id),
  CONSTRAINT fk_filler_entries_dict FOREIGN KEY (dict_id) REFERENCES filler_dicts(id) ON DELETE CASCADE
);